### ISSUE TITLE
Before Checkpoint 2

### ISSUE THREAD

**Issue by www10177** [www10177/3dGameProject#11]
# Todo
明天前要搞定orz

- [x]  將道路的prefab放到目前的道路佈景上（產生車子）

- [x] 起點終點
- [x] 人物視角移調整（攝影機）<-這個應該我負責
- [x] 加入不同車輛（Spawncars部分sciprt需修改，建model）<-感覺也我弄Orz
- [ ] 碰撞？
- [ ] 讓他看起來比較像遊戲一點（？）
- [x]  輸出
# Others
沒那麼緊急
- [x] StartScene要換成這次的
- [x] 道路的高底起伏會造成人物腳陷在裡面，設定collider便可解決，但又會使人物無法移動，猜想調高人物collider是否有用？
- [ ] OutBound
